language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "arc-menu:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
after_success:
- node tasks/ci.js
env:
  global:
  - secure: M0iYkJsjCGRh+c1LLPeZ+piXl1px2pcKHyGW8Yep+RmkFJpHl4giEX2jZ0KY9sO6CavkD7XS6RicjLDfRlOgISF4LtOneZe85rwVWE3GtdY+ZAXuRnTyi8a0s83i7TJQ5vufruuQtcUmYa+2ZHcu/vOMx3F8Tcwo6IIz+Yyu/aKUtaESQs6vaFNFocAi2N8vtpRUzHfstPAB09BBby1qQI79cVJquGkCOduKAU40GXMXqAmhCYC27UIGx4mH8JOov4IrMNLzzy0V8jvceBU0oMEllcCqhvzkJuNXKnh9ZTrJZmTo67dPczxUJNSobf3GFWS8/OOvH0G2zGk+9BoAdBIZiMYEg09qGl8tNZWNR4nt5xL85dKyxXeDgakewnBVTu+zQ2yaL+1KfFZ0RmV+t4dCqTzq2fBmzaHCOaOPsNs7cPRfPiKvbEkrB4aLYS59uq41C+2DgxiLpjeuLWywuwljRUo7/L1NhQgXHcw+LPO+AWZyGhsAj4xYgMAm0f6sZfU8/YRjXrNI8KP7J3FjCAPlwnhokpzUna0TfaWlPXwO4etUANdq7qvgO5jtm5BUDthG5JdWLoiCh9DMVeEfCAtHuDBAC2HQ+9ALVFo6bpX7OLjh15w0EFPILvfabZjnDRpMzlm9doypQaTj5G2HAKCg3Hw8Y+r5LSZ3BJJ7G1o=
  - secure: gfxiC/QxiAUTawLbB18O2qRyKiSkUjvn4ClZAdBo6UkOiTa8kgyP/oZ9j775PPons7T4UiJ5IdrnTyiog1bpAgUO4SyE+bjBk7u+0+scVaJK821yM/tnUXOkPD3G2g5a52oS2mcTUTRHy87qe8fula7d3+wymrGGNmxK97qhwotXI6rVups5ctW/2sGe4PjVQXtzpIhmV6K+Xkeag/kTZuRQDH6vRRfT6246r8lw2NQ5eU4QUxOLqfJ1haEiM1SlDqr/ivmW8NP0lU8GBJy8zJukSPiKKa4tR2gdnFY+MHR/IYx5T5SdirCWC006on6/6A9+P/FuuDACDZIYRBqYotP6xVd5tkhIewJMx8st35vNKgtX96gqFlG3cHmdjXY+pcHYL0o1rTkWaeE9/XYchlZsC64pga7GpYGpcEXWITm+E8O+3fpZRl8JB7E8U3Lbp6+UE8NKG3s6KnjgfmT9/QSwn3iU79wpllXYNx8LeBXCE1aGhKdrevTCPoqjjTBGfgbTc2Oiz5jHv+K7mTQ7/U+vImEzcrHmVbZ72WA5yL1H6kEbCIJFt5lBnyH2cC4zaqw+RpDkjhaSXR3DckCuPtc4NIRBTipbp2TGeRBQtg9O0dlIpYm6XNAWoi8ambBZMC8PfVBMBBR4V6KW2KAEM4iwEHfh3oMza7vjjbct6Io=
